// tag::DE[]
=== Voraussetzungen

Teilnehmerinnen und Teilnehmer **sollten** folgende Kenntnisse und/oder Erfahrung mitbringen:

- Grundlegendes Verständnis für Software-Architektur und typische
Herausforderungen in diesem Feld
- Erfahrung mit den typischen Herausforderungen und Ansätzen bei der
Arbeit an Architekturen im Projektalltag.

**Hilfreich** für das Verständnis einiger Konzepte sind darüber hinaus:

- Arbeit in Gruppen:
* Erfahrung und Kenntnisse von Moderationsmethoden
* Erfahrung und Kenntnisse über die Strukturierung und Durchführung von Meetings
- Architekturarbeit
* Erfahrung und Kenntnisse über die Dokumentation und Visualisierung
von Software, insbesondere Architekturen
- Soziotechnische Belange
* Kenntnisse über Soziotechnik und ihre Auswirkungen auf
Architekturarbeit und Software-Entwicklung.
// end::DE[]

// tag::EN[]
=== Prerequisites

Participants should have the following knowledge and/or experience:

- A basic understanding of software architecture and the typical challenges in this field.
- Practical experience with the common challenges and approaches involved in architectural work in software projects.

The following knowledge is **helpful** for understanding some of the concepts covered in the module:

- Working with Groups:
* Experience with and knowledge of facilitation techniques.
* Experience with and knowledge of structuring and running effective meetings.
- Architecture Work
* Experience with and knowledge of documenting and visualizing software systems, particularly software architectures.
- Sociotechnical Aspects
* A basic understanding of sociotechnical systems and their impact on software architecture and software development.
// end::EN[]
